- components/bl-backdrop-component/component.json
> BKNDLSS-29572 Backdrop Spinner

- components/bl-badge-component/preview.html
> BKNDLSS-29673 Badge

- components/bl-webcamPhoto-component/styles/index.less
> BKNDLSS-29592 Webcam photo

- components/bl-webcamPhoto-component/component.json
> BKNDLSS-29594 Webcam photo

- components/bl-webcamPhoto-component/src/index.js
> BKNDLSS-29593 Webcam photo

- components/bl-backdrop-component/component.json
> BKNDLSS-29569 Backdrop Spinner

- components/bl-draggable-list-component/README.md
- components/bl-draggable-list-component/src/list-item.js
> BKNDLSS-29803 Drag and drop list

- components/bl-rich-editor-component/README.md
- components/bl-rich-editor-component/styles/index.less
> BKNDLSS-30618 Rich Editor

- components/bl-treeSelect-component/src/helpers.js
- components/bl-treeSelect-component/src/index.js
- components/bl-treeSelect-component/styles/index.less
Merge only after PR below has been merged.
[MARKET-1615 On Change Event should return value not key](https://github.com/Backendless/ui-builder-library/pull/237)
> MARKET-1613 Tree Select returns "empty" text for invalid selected option

- components/bl-multiple-select-component/component.json
- components/bl-multiple-select-component/src/helpers/validate.js
- components/bl-multiple-select-component/src/index.js
Link to UI Builder - https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/multiple-select
> BKNDLSS-31144 Purpose of "value" select in settings

- components/bl-rich-editor-component/README.md
- components/bl-rich-editor-component/src/toolbar.js
- components/bl-rich-editor-component/src/use-quill-library.js
- components/bl-rich-editor-component/styles/index.less
UI Builder:
https://develop.backendless.com/app/serhiy_melnychuk_components/ui-builder/bl-rich-editor-component/pages/landing
> BKNDLSS-31219 [Rich Editor] Saved from Editor HTML file don't saves some properties

- components/bl-data-grid-component/src/index.js
UI Builder - https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/data-grid
> MARKET-1657 Data Grid. Handlers should override settings

- components/bl-data-grid-component/src/empty-message.js
- components/bl-data-grid-component/src/index.js
UI Builder - https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/data-grid
> MARKET-1661 [Data Grid] With empty data

- components/bl-double-calendar-component/README.md
- components/bl-double-calendar-component/component.json
- components/bl-double-calendar-component/src/date-range.js
- components/bl-double-calendar-component/src/index.js
> MARKET-1732 [Double Calendar] Add actions to the Double Calendar component

- components/bl-inputWithMask-component/preview.html
> MARKET-1775 [Input with Mask] Add component preview

- components/bl-treeSelect-component/styles/index.less
> MARKET-1798 [TreeSelect] Extra empty space when the search filter is off.

- components/bl-data-grid-component/src/index.js
UI Builder - https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/data-grid
> MARKET-1805 [Data Grid] The Search filter activates from one letter without "Enter".

- components/bl-autocomplete-component/styles/index.less
UI Builder - https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/autocomplete
> MARKET-1802 [Autocomplete] Placeholder overlaps when the dropdown is open.

- components/bl-double-calendar-component/src/date-range.js
> MARKET-1735 [Double Calendar] Logic for reset button

- components/bl-double-calendar-component/src/date-range.js
- components/bl-double-calendar-component/src/index.js
- components/bl-double-calendar-component/styles/index.less
> MARKET-1734 [Double Calendar] Default opening for double calendar

- components/bl-double-calendar-component/src/date-range.js
- components/bl-double-calendar-component/src/helpers/index.js
- components/bl-double-calendar-component/src/helpers/use-actions.js
- components/bl-double-calendar-component/src/helpers/utils.js
> MARKET-1738 [Double Calendar]it is possible to select 2 dates so that DAYS AMOUNT will be less than 0

- components/bl-data-grid-component/src/use-styles.js
UI Builder - https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/data-grid
> MARKET-1819 [Data Grid] Dimension fields can't take on values without "px".

- components/bl-double-calendar-component/src/date-range.js
> [Double-Calendar] Redirect calendar page to selected date if user used set from/to date actions

- components/bl-double-calendar-component/src/date-range.js
> MARKET-1737 [Double Calendar] Add check box in the setting to display/ not display DAYS AMOUNT

- components/bl-innerImageZoom-component/README.md
- components/bl-innerImageZoom-component/component.json
[MARKET-1832](https://bugs.backendless.com/browse/MARKET-1832)
> MARKET-1832 [Inner Image Zoom] Let's make right naming for component

- components/bl-double-calendar-component/src/date-range.js
- components/bl-double-calendar-component/src/helpers/use-actions.js
- components/bl-double-calendar-component/styles/react-datepicker.less
> MARKET-1837 [Double Calendar] Dates displayed as selected after clicking on the reset button

- components/bl-double-calendar-component/src/helpers/utils.js
> [Double Calendar] Add the ability to use different separators

- components/bl-pdfViewer-component/README.md
- components/bl-pdfViewer-component/src/index.js
- components/bl-pdfViewer-component/src/subcomponents.js
- components/bl-pdfViewer-component/styles/index.less
> [PDF Viewer] Error after changing the display to false

- components/bl-rich-editor-component/src/index.js
- components/bl-rich-editor-component/src/use-quill-library.js
[UI Builder](https://develop.backendless.com/app/serhiy_melnychuk_components/ui-builder/bl-rich-editor-component/pages/landing)
[Desktop Preview](https://genteelinstrument.backendless.app/api/files/ui-builder/containers/bl-rich-editor-component/index.html?page=landing)
> BKNDLSS-31766 [Support] [Rich Editor] Prevent XSS attacks

- components/bl-double-calendar-component/README.md
- components/bl-double-calendar-component/src/index.js
- components/bl-double-calendar-component/src/specific-date-range.js
[UI Builder](https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/double-calendar)
> MARKET-1865 [Double Calendar] Add handler in logic to select start date for specific date range

- components/bl-modal-component/README.md
- components/bl-modal-component/component.json
- components/bl-modal-component/src/index.js
[UI Builder](https://develop.backendless.com/app/zahar_mychka_components/ui-builder/default/pages/modal)
> MARKET-1693 [Modal] Visibility logic does not work

- components/bl-carousel-component/README.md
- components/bl-carousel-component/src/helpers.js
- components/bl-carousel-component/src/index.js
- components/bl-carousel-component/src/subcomponents.js
- components/bl-carousel-component/styles/index.less
> MARKET-1891 [Carousel] Buttons and labels are invisible on the white background.

- components/bl-collapsiblePanel-component/README.md
- components/bl-collapsiblePanel-component/styles/index.less
[MARKET-1975](https://bugs.backendless.com/browse/MARKET-1975)
> MARKET-1975 [Collapsible Panel] Some styles work wrong.

- components/bl-snackbar-component/README.md
- components/bl-snackbar-component/component.json
- components/bl-snackbar-component/src/index.js
- components/bl-snackbar-component/src/snackbar.js
- components/bl-snackbar-component/styles/index.less
> BKNDLSS-32602 [Snackbar] Add the "Outline frame" to the options and Styles.

- components/bl-audio-recorder-component/src/index.js
> MARKET-1979 [Audio Recorder] Change the Buttons positions.

- components/bl-weather/README.md
README.md updated
[MARKET-2030](https://bugs.backendless.com/browse/MARKET-2030)
> MARKET-2030 [Weather] Component doesn't work with free API key

- components/bl-weather/styles/index.less
Added styles for correct display of the main weather icon
[MARKET-2097](https://bugs.backendless.com/browse/MARKET-2097)
> MARKET-2097 [Weather] Cloud image cut.

- components/bl-spoiler/component.json
[MARKET-2137](https://bugs.backendless.com/browse/MARKET-2137)
> MARKET-2137 [Spoiler effect] The same ID with the "Animated box" component.

- components/bl-granim/src/index.js
[MARKET-2158](https://bugs.backendless.com/browse/MARKET-2158)
> MARKET-2158 [Granim] App crash when the visible is disabled.

- components/bl-granim/README.md
- components/bl-granim/src/index.js
- components/bl-granim/styles/index.less
[MARKET-2161](https://bugs.backendless.com/browse/MARKET-2161)
Updated styles, readme, added lost dependency
> MARKET-2161 [Granim] Size style incorrectly work with the percentage.

- components/bl-animated-box/README.md
- components/bl-animated-box/styles/index.less
[MARKET-2168](https://bugs.backendless.com/browse/MARKET-2168)
Redundant variables removed.
Updated styles, readme.
> MARKET-2168 [Animated Box] Remove Other from Styles

- components/bl-animated-box/README.md
> animated box Update README.md

- components/bl-spoiler/README.md
- components/bl-spoiler/component.json
- components/bl-spoiler/src/index.js
[MARKET-2178](https://bugs.backendless.com/browse/MARKET-2178)
Removed event, fixed set state name in toggle action, updated component.json, readme
> MARKET-2178 [Spoiler] Remove the "Mouse move" event

- components/bl-spoiler/src/effects.js
[MARKET-2179](https://bugs.backendless.com/browse/MARKET-2179)
updated blured effect
> MARKET-2179 [Spoiler] The Blur Effect works incorrectly with text.

- components/bl-spoiler/README.md
- components/bl-spoiler/component.json
- components/bl-spoiler/src/index.js
- components/bl-spoiler/styles/index.less
[MARKET-2183](https://bugs.backendless.com/browse/MARKET-2183)
default background value changed, extra styles and classes removed, component update, readme update
> MARKET-2183 [Spoiler] Make the transparent color as default.

- components/bl-collapsible-panel/README.md
- components/bl-collapsible-panel/styles/index.less
[MARKET-2187](https://bugs.backendless.com/browse/MARKET-2187)
> MARKET-2187 [Collapsible panel] (Support) Add new styles.

- components/bl-dashlet/README.md
> Update [Dashlet] README.md

- components/bl-sweet-alert/README.md
- components/bl-sweet-alert/styles/index.less
[MARKET-2204](https://bugs.backendless.com/browse/MARKET-2204)
> MARKET-2204 [Sweet Alert] Footer layout shift on the mobile view.

- components/bl-ace-editor/component.json
> MARKET-2225 [Ace Editor] Add the tooltip to ALL settings with description.

- components/bl-audio-player/README.md
- components/bl-carousel/README.md
- components/bl-cropper/README.md
- components/bl-radio-buttons-list/README.md
- components/bl-treemap/README.md
> Demo Arcades added to the readme

- components/bl-timer/src/index.js
UI-Builder: https://develop.backendless.com/app/pavlo_stasiv_components/ui-builder/Timer/pages/landing
> MARKET-2247 [Timer] The "On Timer End" event works wrong.

- components/bl-navigation-dots/styles/index.less
[MARKET-2285](https://bugs.backendless.com/browse/MARKET-2285)
> MARKET-2285 [Navigation Dots] The component isn't clickable.

- components/bl-credit-card/README.md
- components/bl-list/README.md
- components/bl-markdown/README.md
- components/bl-marquee/README.md
- components/bl-parallax/README.md
- components/bl-snackbar/README.md
- components/bl-tabs/README.md
- components/bl-totop/README.md
- components/bl-transitions/README.md
- components/bl-tree-view/README.md
Add links to Arcades for UI Components to their GitHub documentation page.
> MARKET-2236

- components/bl-pagination/README.md
- components/bl-static-breadcrumbs/README.md
> Readme demo added (arcades) (6)+2new

- components/bl-tabs/README.md
[BKNDLSS-34356](https://bugs.backendless.com/browse/BKNDLSS-34356)
> BKNDLSS-34356 [Tabs] Add "Try youself" code blocks in the readme file.

- components/bl-avatar/README.md
- components/bl-data-grid/README.md
- components/bl-popover/README.md
- components/bl-re-captcha/README.md
- components/bl-rich-editor/README.md
Data Grid
reCaptcha
Popover
Rich Editor
Avatar
> Readme demo added (arcades) 7th wave

- components/bl-animated-box/README.md
- components/bl-audio-recorder/README.md
- components/bl-category-chart/README.md
- components/bl-dropzone/README.md
- components/bl-granim/README.md
- components/bl-leaflet-map/README.md
> Readme demo added (arcades) 8th wave

- components/bl-collapsible-panel/README.md
- components/bl-dashlet/README.md
- components/bl-modal/README.md
- components/bl-multiple-select/README.md
- components/bl-simple-modal/README.md
- components/bl-spoiler/README.md
- components/bl-sweet-alert/README.md
> Readme demo added (arcades) 9th wave

- components/bl-ace-code-editor/README.md
- components/bl-autocomplete/README.md
- components/bl-avatar-generator/README.md
- components/bl-input-with-mask/README.md
- components/bl-navigation-dots/README.md
- components/bl-particles/README.md
- components/bl-skeleton/README.md
- components/bl-stopwatch/README.md
https://bugs.backendless.com/browse/MARKET-2236
> Readme demo added (arcades) 10th wave
